### ISSUE TITLE
Empty output

### ISSUE THREAD

**Issue by nicotel** [diriano/ploidyNGS#11]
Hello, 

the output file .tab is generated nevertheless it remains empty, no errors or warnings are printed out.
trying to figure out the reason .. both installation and test went well. 

thank you for your time

**Comment by Pikayy** [comment]
Hi,

I am wondering if you have got the problem fixed? I had exactly the same issue.

Best

**Comment by karlcou** [comment]
Hi, 

I guess I'm having the same issues. Anytime I'm running PloidyNGS, my pdf files remains an empty grid. 

Thanks !

**Comment by Jwebster89** [comment]
Late to the party here, but I came across the same issue. I made the following change in ploidyNGS_generateHistogram.R and commented out the original line. I'm not sure if not changing the factor levels will break or change something later, but it at least made my pdf not an empty grid.

`#datain$Type = factor(datain$Type,
                     #levels(datain$Type)[c(1,3,4,2)])`

`datain$Type = factor(datain$Type)`
