### ISSUE TITLE
Biopython Python3 <> Python2

### ISSUE THREAD

**Issue by ziejan** [diriano/ploidyNGS#15]
Hey there,

I want to run your Software but cant get it done because it says: "This script requires Python version 2.7.8 or higher within major version 2" where as Biopython (which is needed for your Software: "from Bio.SeqRecord import SeqRecord") needs Python 3.6 or later: "Biopython requires Python 3.6 or later. Python 2.7 detected."

Is there any solution?

**Comment by diriano** [comment]
HI @ziejan,
I have just uploaded a new version that uses python3, please let me know how that works for you.
Diego
