### ISSUE TITLE
About ploidyNGS.py

### ISSUE THREAD

**Issue by EugeneKim76** [diriano/ploidyNGS#20]
Dear all
I recently tested ploidyNGS, and found an error message below.

1. commend line
./ploidyNGS.py -o diploidTest -b test_data/simulatedDiploidGenome/Ploidy2.bowtie2.sorted.bam
2. error message
sh: 1: ploidyNGS_generateHistogram.R: not found

So, I suggest to fix ploidyNGS.py (line229)  as shown below.

original : cmdPloidyGraphRscript="ploidyNGS_generateHistogram.R "
fixed : cmdPloidyGraphRscript="Rscript ploidyNGS_generateHistogram.R "

Best,

**Comment by SantosRAC** [comment]
Thanks @EugeneKim76 ! I apologize for taking a looong time to answer, but thanks ! I fixed the problem and tried to run and it really solved the problem.
