### ISSUE TITLE
where is explorePloidyNGS.py?

### ISSUE THREAD

**Issue by mikheyev** [diriano/ploidyNGS#5]
The [simulation page](https://github.com/diriano/ploidyNGS/blob/master/simulation/results/results_ploidy_simulations.html) mentions a useful-sounding script called `explorePloidyNGS.py`, but I can't seem to find it in the repository.

**Comment by diriano** [comment]
Dear Alexander,

in the latest version of our software, that script became ploidyNGS.py. We should update the HTML file to reflect that.

Cheers,

Diego

**Comment by diriano** [comment]
The simulation page was updated to reflect the change of name of the main script.
