### ISSUE TITLE
#Not an issue, but needed help to comment on ploidy of an organism.

### ISSUE THREAD

**Issue by bhagya-ct** [diriano/ploidyNGS#7]
Dear Developer,
#sorry to raise an issue unnecessarily.

Below is what I got when I ran the tool, 
(.venv) mml@MML:~/softwares/ploidyNGS$ ./ploidyNGS.py --guess_ploidy -o guess_test -b dedup_SS_BWA_reads.bam 
###############################################################
###############################################################
BAM index present... OK!
Number of mapped reads from BAM: 3483177
Observed average coverage: 54.00
Coverage used for guessing ploidy: 50

  After comparing your data with our simulated dataset
  and computing the Kolmogorov-Smirnov distance, 
  the closest ploidy to yours is 3

And the image generated is attached below.

In the scientific field, confusion is haploid? or diploid?

Little information about the organism:
Fungi, 12.5mb genome, Illumina Miseq paired end reads.

Please go through the image and let me know what do you think.

Thanks 
Bhagya C T

[guessnoidea_test_depth100.tab.PloidyNGS.pdf](https://github.com/diriano/ploidyNGS/files/1471964/guessnoidea_test_depth100.tab.PloidyNGS.pdf)

**Comment by diriano** [comment]
Dear Bhagya,

no need to raise an issue for this. You can contact us via e-mail. Check our paper to get the contact details.

Did you mask your genome? That is important to eliminate false polymorphisms. Perhaps trying individually on the largest contigs will give a clearer idea.

Cheers,
Diego
