### ISSUE TITLE
Error Message - ZeroDivisionError: integer division or modulo by zero

### ISSUE THREAD

**Issue by etvedte** [diriano/ploidyNGS#8]
Greetings,

I'm trying to use ploidyNGS to make predictions about putatively haploid/diploid datasets. I followed the documentation and received the following error:

 ./ploidyNGS.py --guess_ploidy -o DF_genome -d 100000 -b DF_I_DNA_genome_SORTED.bam
###############################################################
###############################################################
BAM index present... OK!
Number of mapped reads from BAM: 31817941
Traceback (most recent call last):
  File "./ploidyNGS.py", line 130, in <module>
    averageCoverage=countTotalReads/countTotalPositions
ZeroDivisionError: integer division or modulo by zero

I'm guessing by the error output that the denominator in averageCoverage is zero, but that shouldn't be the case. My bam file contains a large eukaryotic genome with lots of scaffolds, but I wanted to test using the -d flag as a first pass before splitting bam into scaffolds. Any help is appreciated!

**Comment by diriano** [comment]
you may have scaffold with very low coverage, and these are giving rise to the problem. I would suggest to run ploidyNGS on well covered scaffolds, at least 50x.

**Comment by aldembert** [comment]
Ok thanks a lot Diego!
