### ISSUE TITLE
Did you checked the haploid example?

### ISSUE THREAD

**Issue by aldembert** [diriano/ploidyNGS#9]
When I run the haploid test data it gives a ploidy of 6 when using -g option but the histogram shows a clear haploid ploidy, can you check that?

**Comment by nsarode-joyn** [comment]
I am having the same issue. The haploid test dataset doesn't match the example output.

**Comment by chiu-shenpo** [comment]
I faced the same problem, please fix this

**Comment by diriano** [comment]
Please check the section 'Important note on ploidy guessing with ploidyNGS'
